name: Scheduled deployment of FMU binaries from develop

# Note: this workflow will eventually disappear as soon as the AuterionOS
# release container fetches the binaries directly from Artifactory

on:
  schedule:
    - cron: '0 9 * * 1' # At 09:00 on Mondays, trigger PR to AuterionOS

jobs:
  deploy:
   runs-on: ubuntu-latest
   container: px4io/px4-dev-nuttx-focal:2021-09-08
   steps:
    - uses: actions/checkout@v1
    - name: Disable the keychain credential helper
      run: git config --global credential.helper ""
    - name: Enable the local store credential helper
      run: git config --global --add credential.helper store
    - name: Add credential
      run: echo "https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com" >> ~/.git-credentials
    - name: Tell git to use https instead of ssh whenever it encounters it
      run: 'git config --global url."https://github.com/".insteadof git@github.com:'
    - name: Get submodules
      run: 'git submodule update --init --recursive'

    - name: Make Nuttx development targets
      run: |
        ## Create target directory
        mkdir development
        ## Build targets
        make px4_fmu-v5_default
        make px4_fmu-v5_rtps
        make px4_fmu-v5x_default
        make px4_fmu-v5x_rtps
        ## Move target resulting artifacts to the development folder
        mv build/* development/

    - name: Make Nuttx production targets
      run: |
        ## Create target directory
        mkdir production
        ## Build targets
        PX4_RESTRICTED_BUILD=1 make px4_fmu-v5_default
        PX4_RESTRICTED_BUILD=1 make px4_fmu-v5_rtps
        PX4_RESTRICTED_BUILD=1 make px4_fmu-v5x_default
        PX4_RESTRICTED_BUILD=1 make px4_fmu-v5x_rtps
        ## Move target resulting artifacts to the production folder
        mv build/* production/

    - name: Clone AuterionOS
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        repository: Auterion/AuterionOS
        path: distro/

    - name: Update binaries in AuterionOS
      id: update_binaries
      run: |
        yes | cp -rf development/*/px4_fmu-v5*.px4 distro/src/fmu/binaries/dev
        yes | cp -rf production/*/px4_fmu-v5*.px4 distro/src/fmu/binaries/prod
        echo "::set-output name=timestamp::$(date)"

    - name: Create PR to AuterionOS repo
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        path: distro/
        title: "Update FMU binaries to latest develop | ${{ steps.update_binaries.outputs.timestamp }}"
        body: "Updates FMU binaries from latest APX4 develop build. Created in ${{ steps.update_binaries.outputs.timestamp }}."
        reviewers: DanielePettenuzzo,ThomasDebrunner
        commit-message: "src: fmu: update binaries to latest develop"
        author: auterionci <ci@auterion.com>
        committer: auterionci <ci@auterion.com>
        base: master
        branch: pr-update_fmu_binaries_develop
